### ISSUE TITLE
Error when trying to use the "hello wordl dragonfly" grammar

### ISSUE THREAD

**Issue by piotrpalek** [dictation-toolbox/aenea#152] opened 2017-11-16 22:04 UTC
Hey I'm getting this error when trying to load the `_hello_world_dragonfly.py` grammar:

`-- skip unchanged wrong grammar file: C:\NatLink\NatLink\MacroSystem\_hello_world_dragonfly.py`

Can somebody help me with this? The `_hello_world_natlink.py` file loaded fine :(

**Comment by facundoq** [comment] 2019-08-06 13:40
It's likely that DragonFly has not been installed properly. So natlink is working but dragonfly is not.

**Comment by LexiconCode** [comment] 2019-08-06 14:46
Make sure you're not using the original dragonfly `pip uninstall dragonfly` then use `pip install dragonfly2`

**Comment by Danesprite** [comment] 2019-08-14 12:36
Sorry, I referenced the wrong issue from that PR. Either version of dragonfly would work with that grammar, but dragonfly2 is better.

Should this issue be closed? It's from quite a while ago and is probably only caused by `dragonfly` not being installed.

**Comment by calmofthestorm** [comment] 2019-11-30 03:06
I think we can close this. Please feel free to reopen if there's anything else here to discuss.

**Closed by calmofthestorm** 2019-11-30 03:06 UTC
